---
# tasks file for hostnames

- name: set hostname as per ansible inventory
  hostname:
    name: "{{ inventory_hostname_short }}"
  tags: hostname

- name: update hostname in /etc/hosts from inventory
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
    state: present
  tags: hostname

- name: add long-hostname option to getty login
  copy:
    src: getty@tty1.service.d/
    dest: /etc/systemd/system/getty@tty1.service.d/
    mode: 0644
    owner: root
    group: root
  notify:
    - restart getty
  tags:
    - tty

- name: deploy bashrc to root
  copy:
    src: bashrcs/bashrc_root
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0644

- name: deploy bashrc to skel
  copy:
    src: bashrcs/bashrc_user
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: 0644
