---
# tasks file for hostnames

- name: set hostname as per ansible inventory
  hostname:
    name: "{{ inventory_hostname_short }}"
  tags:
    - hostname

- name: update hostname in /etc/hosts from inventory
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
    state: present
  tags:
    - hostname

- name: add long-hostname option to getty login
  copy:
    src: getty@tty1.service.d/
    dest: /etc/systemd/system/getty@tty1.service.d/
    mode: 0644
    owner: root
    group: root
  notify:
    - restart getty
  tags:
    - tty

- name: deploy ps1.sh prompt script to /etc/profile.d
  copy:
    src: ps1.sh
    dest: /etc/profile.d/
    owner: root
    group: root
    mode: 0644
  tags:
    - ps1
